package com.sxkl.cloudnote.eventdriven.entity;

public enum DutyType {

	INCREASE_HITNUM,LINK_ARTICLE_IMAGE,
	UPDATE_INDEX_BY_DELETE_OPERATION,UPDATE_INDEX_BY_ADD_OPERATION,
	UPDATE_INDEX_BY_UPDATE_OPERATION;
}
